# Generated by Django 5.1.5 on 2025-01-27 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_search_vector_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveIndex(
            model_name='document',
            name='documents_d_search__05a045_gin',
        ),
        migrations.RemoveField(
            model_name='document',
            name='search_vector',
        ),
    ]
