# Generated by Django 5.1.5 on 2025-01-27 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_document_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('VIEW', 'View Only'), ('COMMENT', 'Comment'), ('EDIT', 'Edit'), ('MANAGE', 'Manage')], default='VIEW', max_length=10)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valid_until', models.DateTimeField(blank=True, help_text='Leave empty for indefinite access', null=True)),
                ('is_active', models.BooleanField(default=True, help_text="Inactive shares don't grant access")),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='documents.document')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_documents', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shared Document',
                'verbose_name_plural': 'Shared Documents',
                'ordering': ['-shared_at'],
                'unique_together': {('document', 'shared_with')},
            },
        ),
        migrations.AddField(
            model_name='document',
            name='shared_users',
            field=models.ManyToManyField(related_name='shared_with_me', through='documents.SharedDocument', to=settings.AUTH_USER_MODEL),
        ),
    ]
